= I. Определения

== 1. Понятия 
	* *Ход* - период времени, за который возможно перемещение Kuvahaku на 1 клетку.
	* *Ячейка* - квадратная область, в которой может находится часть или цельная (в случае с Kuvahaku) Сущность.
	* *Стэк Ячеек* - количество свободных Ячеек, в котором может находиться Сущность. 
	* *Поле* - набор Ячеек, в пределах которого может осуществляться перемещение и взаимодействие Сущностей.
	* *Сущность* - любой живой организм данного Поля. 
	* *Сущность-Родитель* - пара Сущностей одного типа, которые создали новую Сущность своего типа.
	* *Сущность-Потомок* - новая Сущность созданная парой Сущностей-Родителей, того же типа, что и они.
	* *Kuvahaku* - маленькая Сущность размера 1x1 Ячейки, изначально существовала в Поле, способна к репродукции.
	* *Kuvat* - средняя Сущность размера 2x2 Ячейки, эволюционировавшая из Kuvahaku, способна к репродукции.
	* *Uutiset* - уникальная большая Сущность размера 3x3 Ячейки, пришедшая из другого Поля, не способна к репродукции.
	* *Пара/Пары* [Сущностей] - группа, имеющая угловой или абсолютный контакт двух или кратного двум числа Сущностей одного типа.
	* *Отряд* [Сущностей] - группа Сущностей одного типа, которые контактируют абсолютно с одной Сущностью большего типа.
	* *Сэндвич* [Сущностей] - пара Kuvat, которые контактируют абсолютно с 1-2 Kuvahaku, расположенным между ними.
	* *Радиус Достижения* - группа Стэков Ячеек, в которые Сущность может попасть за 1 ход с учётом её скорости.
	* *Ячейка за Ход* - единица скорости Сущностей. Обозначается *Я/Х*.

== 2. Состояния
	* *Движение* - последовательная смена положения Сущности на Поле от одной Ячейки к другой с учетом скорости данной Сущности.
	* *Абсолютный контакт* - на текущем Ходе Сущности имеют общую (общие) границу (границы) Ячеек.
	* *Угловой контакт* - на текущем Ходе Сущности имеют общую вершину Ячеек (условно: расположены под диагонали относительно друг друга).
	* *Блокировка движения* - на текущем Ходе для Сущности не существует Стэка Ячеек.

== 3. События
	* *Репродукция* - создание новой Сущности того же типа, что и Сущности-Родители.
	* *Поглощение* - уничтожение одной Сущности другой (другими).
	* *Отталкивание* - изменение направления движения Сущности на противоположное. 
	* *Смерть* - исчезновение Сущности не в результате Поглощения.


= II. Правила

== Движение
	. Каждая _Сущность_ движется:
	* _Kuvahaku_: движется к любому _Стэку Ячеек_ в _Радиусе Достижения_ со скоростью 1 Я/Х, обладает способностью “KuvaJump” - движение со скоростью 3 Я/Х раз в 5 Ходов в любую сторону; 
	* _Kuvat_: движется к любому Стэку Ячеек в _Радиусе Достижения_ со скоростью 1 Я/Х;
	* _Uutiset_: движется к любому Стэку Ячеек в _Радиусе Достижения_ со скоростью 2 Я/Х.
	. Если _Сущность_ типа _Kuvahaku_ или _Kuvat_ находится в состоянии _Блокировка движения_ дольше 2 _Ходов_ для неё наступает событие _Смерть_.
	. Если _Сущность_ сталкивается с краем _Поля_, происходит событие _Отталкивание_.

== Контакт 
	. Если _Сущность_ встречается с другой _Сущностью_ возможны 3 события и одно состояние: 
		* _Репродукция_, 
		* _Поглощение_, 
		* _Отталкивание_,
		* _Блокировка движения_.
	. _Репродукция_ возможна при выполнении всех следующих условий:
		* (and) _Сущности_ составляют _Пару/Пары_;
		* (and) Вокруг каждой _Пары_ присутствует _Стэк Ячеек_ подходящего размера для _Сущности-Потомка_:
			** для _Kuvahaku_ - 1 _Ячейка_;
			** для _Kuvat_ - 4 _Ячейки_.
	. _Поглощение_ возможно при выполнении хотя бы одного из следующих условий:
		* (or) _Сущности_ разных типов контактируют абсолютно, при этом большая _Сущность_ поглащает меньшую/меньшие:
			** _Kuvat_ может поглотить 1 _Kuvahaku_;
			** _Uutiset_ может поглотить до 3 _Kuvat_ и до 7 _Kuvahaku_;
		* (or) _Сущности_ составляют _Отряд_, при этом группа меньших _Сущностей_, поглощает большую:
			** _Отряд_ из 2 _Kuvahaku_ может поглотить 1 _Kuvat_;
			** _Отряд_ из 8 _Kuvahaku_ может поглотить _Uutiset_;
			** _Отряд_ из 4 _Kuvat_ может поглотить _Uutiset_;
		* (or) _Сущности_ образуют _Сэндвич_, при этом большие _Сущности_ поглащают меньшую (меньшие).
	. _Блокировка движения_ возможна при контакте данной _Сущности_ с другими _Сущностями_ одного типа, при невозможности событий _Репродукция_.
	. Во всех остальных случаях происходит событие _Отталкивание_.
